/*-
 * SPDX-License-Identifier: BSD 3-Clause License
 *
 * Copyright (c) 2026 deadcafe.beef@gmail.com
 * All rights reserved.
 */

#ifndef _FLOW6_CACHE_H_
#define _FLOW6_CACHE_H_

#include <string.h>
#include <rix/rix_defs.h>
#include <rix/rix_queue.h>
#include <rix/rix_hash.h>

/*===========================================================================
 * IPv6 flow key: 5-tuple + vrfid (44 bytes)
 *===========================================================================*/
struct flow6_key {
    uint8_t  src_ip[16];
    uint8_t  dst_ip[16];
    uint16_t src_port;
    uint16_t dst_port;
    uint8_t  proto;
    uint8_t  pad[3];
    uint32_t vrfid;
};

/*===========================================================================
 * IPv6 flow entry (128 bytes = 2 cache lines)
 *
 * CL0 (0-63):  lookup hot path — accessed during pipelined find
 * CL1 (64-127): counters & management — accessed on hit / eviction
 *===========================================================================*/
struct flow6_entry {
    /* --- CL0: lookup + expire hot path (64 bytes) --- */
    struct flow6_key     key;           /* 44B */
    uint32_t             cur_hash;      /*  4B: hash_field for O(1) remove */
    uint64_t             last_ts;       /*  8B: last access TSC (0 = invalid) */
    RIX_SLIST_ENTRY(struct flow6_entry) free_link;  /* 4B: free list */
    uint8_t              reserved0[4];  /*  4B: pad to 64B */

    /* --- CL1: counters & hit-path data (64 bytes) --- */
    uint32_t             action;        /*  4B: cached ACL result */
    uint32_t             qos_class;     /*  4B: cached QoS class */
    uint64_t             packets;       /*  8B */
    uint64_t             bytes;         /*  8B */
    uint8_t              reserved1[40]; /* 40B: pad to 64B */
} __attribute__((aligned(64)));

/*===========================================================================
 * Key comparison function for RIX_HASH_GENERATE
 *===========================================================================*/
static inline int
flow6_cmp(const void *a, const void *b)
{
    const struct flow6_key *ka = (const struct flow6_key *)a;
    const struct flow6_key *kb = (const struct flow6_key *)b;

    return (memcmp(ka->src_ip, kb->src_ip, 16) == 0 &&
            memcmp(ka->dst_ip, kb->dst_ip, 16) == 0 &&
            ka->src_port == kb->src_port &&
            ka->dst_port == kb->dst_port &&
            ka->proto    == kb->proto    &&
            ka->vrfid    == kb->vrfid);
}

/*===========================================================================
 * Generate hash table functions: flow6_ht_*
 *===========================================================================*/
RIX_HASH_HEAD(flow6_ht);
RIX_HASH_GENERATE(flow6_ht, flow6_entry, key, cur_hash, flow6_cmp)

/*===========================================================================
 * Cache struct, API declarations, and inline helpers
 * — generated by flow_cache_common.h
 *===========================================================================*/
#define FC_PREFIX       flow6
#define FC_ENTRY        flow6_entry
#define FC_KEY          flow6_key
#define FC_CACHE        flow6_cache
#define FC_HT           flow6_ht
#define FC_FREE_HEAD    flow6_free_head
#include "flow_cache_common.h"
#undef FC_PREFIX
#undef FC_ENTRY
#undef FC_KEY
#undef FC_CACHE
#undef FC_HT
#undef FC_FREE_HEAD

#endif /* _FLOW6_CACHE_H_ */

/*
 * Local Variables:
 * c-file-style: "bsd"
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * tab-width: 4
 * End:
 */
