/*-
 * SPDX-License-Identifier: BSD 3-Clause License
 *
 * Copyright (c) 2026 deadcafe.beef@gmail.com
 * All rights reserved.
 */

#ifndef _FLOW6_CACHE_H_
#define _FLOW6_CACHE_H_

#include <string.h>
#include <rix/rix_queue.h>
#include <rix/rix_hash.h>
#include "flow_cache_decl.h"

/*===========================================================================
 * IPv6 flow key: 5-tuple + vrfid (44 bytes)
 *===========================================================================*/
struct flow6_key {
    uint8_t  src_ip[16];
    uint8_t  dst_ip[16];
    uint16_t src_port;
    uint16_t dst_port;
    uint8_t  proto;
    uint8_t  pad[3];    /* must be zero-initialised; included in memcmp */
    uint32_t vrfid;
} __attribute__((packed));

/*===========================================================================
 * IPv6 flow entry (128 bytes = 2 cache lines)
 *
 * CL0 (0-63):  lookup hot path - accessed during pipelined find
 * CL1 (64-127): user payload - managed by init_cb / fini_cb callbacks
 *===========================================================================*/
struct flow6_entry {
    FLOW_CACHE_CL(0);                   /* lookup + expire hot path */
    struct flow6_key     key;           /* 44B */
    uint32_t             cur_hash;      /*  4B: hash_field for O(1) remove */
    uint64_t             last_ts;       /*  8B: last access TSC (0 = invalid) */
    RIX_SLIST_ENTRY(struct flow6_entry) free_link;  /* 4B: free list */
    uint8_t              reserved0[4];  /*  4B: pad to 64B */

    FLOW_CACHE_CL(1);                   /* user payload (64B, caller-defined) */
    union {
        uint8_t  u8[64];               /* byte access */
        uint64_t u64[8];               /* 8B-aligned: cast to user struct safely */
    }                    userdata;
} __attribute__((aligned(FLOW_CACHE_LINE_SIZE)));

/*===========================================================================
 * Key comparison: full 44-byte memcmp.
 *
 * Correct because the struct is packed (no implicit padding) and pad[3]
 * is always zero-initialised by callers before setting any field.
 * The compiler inlines this as five 8-byte and one 4-byte comparisons,
 * or as two 256-bit SIMD loads when AVX2 is available.
 *===========================================================================*/
static inline int __attribute__((nonnull(1,2)))
flow6_cmp(const void *a, const void *b)
{
    return memcmp(a, b, sizeof(struct flow6_key));
}

/*===========================================================================
 * Hash table head type: flow6_ht
 * RIX_HASH_GENERATE is expanded in each *.c that needs the implementations.
 *===========================================================================*/
RIX_HASH_HEAD(flow6_ht);

/*===========================================================================
 * Cache struct, API declarations, and inline helpers
 * - generated by flow_cache_decl.h
 *===========================================================================*/
#define FC_PREFIX       flow6
#define FC_ENTRY        flow6_entry
#define FC_KEY          flow6_key
#define FC_CACHE        flow6_cache
#define FC_HT           flow6_ht
#define FC_FREE_HEAD    flow6_free_head
#include "flow_cache_decl.h"
#undef FC_PREFIX
#undef FC_ENTRY
#undef FC_KEY
#undef FC_CACHE
#undef FC_HT
#undef FC_FREE_HEAD

#endif /* _FLOW6_CACHE_H_ */

/*
 * Local Variables:
 * c-file-style: "bsd"
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * tab-width: 4
 * End:
 */
