/*-
 * SPDX-License-Identifier: BSD 3-Clause License
 *
 * Copyright (c) 2026 deadcafe.beef@gmail.com
 * All rights reserved.
 */

#ifndef _FLOW4_CACHE_H_
#define _FLOW4_CACHE_H_

#include <rix/rix_queue.h>
#include <rix/rix_hash.h>
#include "flow_cache_defs.h"

/*===========================================================================
 * IPv4 flow key: 5-tuple + vrfid (20 bytes)
 *===========================================================================*/
struct flow4_key {
    uint32_t src_ip;
    uint32_t dst_ip;
    uint16_t src_port;
    uint16_t dst_port;
    uint8_t  proto;
    uint8_t  pad[3];
    uint32_t vrfid;
} __attribute__((packed));

/*===========================================================================
 * IPv4 flow entry (128 bytes = 2 cache lines)
 *
 * CL0 (0-63):  lookup hot path - accessed during pipelined find
 * CL1 (64-127): counters & management - accessed on hit / eviction
 *===========================================================================*/
struct flow4_entry {
    FLOW_CACHE_CL(0);                   /* lookup + expire hot path */
    struct flow4_key     key;           /* 20B */
    uint32_t             cur_hash;      /*  4B: hash_field for O(1) remove */
    uint64_t             last_ts;       /*  8B: last access TSC (0 = invalid) */
    RIX_SLIST_ENTRY(struct flow4_entry) free_link;  /* 4B: free list */
    uint8_t              reserved0[28]; /* 28B: pad to 64B */

    FLOW_CACHE_CL(1);                   /* counters & management */
    uint32_t             action;        /*  4B: cached ACL result */
    uint32_t             qos_class;     /*  4B: cached QoS class */
    uint64_t             packets;       /*  8B */
    uint64_t             bytes;         /*  8B */
    uint8_t              reserved1[40]; /* 40B: pad to 64B */
} __attribute__((aligned(FLOW_CACHE_LINE_SIZE)));

/*===========================================================================
 * Key comparison function for RIX_HASH_GENERATE
 *===========================================================================*/
static inline int __attribute__((nonnull(1,2)))
flow4_cmp(const void *a, const void *b)
{
    const struct flow4_key *ka = (const struct flow4_key *)a;
    const struct flow4_key *kb = (const struct flow4_key *)b;

    return (ka->src_ip   == kb->src_ip   &&
            ka->dst_ip   == kb->dst_ip   &&
            ka->src_port == kb->src_port &&
            ka->dst_port == kb->dst_port &&
            ka->proto    == kb->proto    &&
            ka->vrfid    == kb->vrfid);
}

/*===========================================================================
 * Hash table head type: flow4_ht
 * RIX_HASH_GENERATE is expanded in each *.c that needs the implementations.
 *===========================================================================*/
RIX_HASH_HEAD(flow4_ht);

/*===========================================================================
 * Cache struct, API declarations, and inline helpers
 * - generated by flow_cache_common.h
 *===========================================================================*/
#define FC_PREFIX       flow4
#define FC_ENTRY        flow4_entry
#define FC_KEY          flow4_key
#define FC_CACHE        flow4_cache
#define FC_HT           flow4_ht
#define FC_FREE_HEAD    flow4_free_head
#include "flow_cache_common.h"
#undef FC_PREFIX
#undef FC_ENTRY
#undef FC_KEY
#undef FC_CACHE
#undef FC_HT
#undef FC_FREE_HEAD

#endif /* _FLOW4_CACHE_H_ */

/*
 * Local Variables:
 * c-file-style: "bsd"
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * tab-width: 4
 * End:
 */
